//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitechCraft.WebApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HitechCraft.WebApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль с данным именем уже существует.
        /// </summary>
        public static string Administration_AddRole_ErrorAlreadyExists {
            get {
                return ResourceManager.GetString("Administration_AddRole_ErrorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить уникальность.
        /// </summary>
        public static string CheckUserName {
            get {
                return ResourceManager.GetString("CheckUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Ник.
        /// </summary>
        public static string EmailOrNickName {
            get {
                return ResourceManager.GetString("EmailOrNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы клиента будут перезакачены.
        /// </summary>
        public static string ErrorClientFilesCheck {
            get {
                return ResourceManager.GetString("ErrorClientFilesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для авторизации необходимо подтвердить Email {0}.
        /// </summary>
        public static string ErrorEmailNotConfirmed {
            get {
                return ResourceManager.GetString("ErrorEmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина {1}.
        /// </summary>
        public static string ErrorMinLength {
            get {
                return ResourceManager.GetString("ErrorMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль и его подтверждение не совпадают.
        /// </summary>
        public static string ErrorPasswordsCompare {
            get {
                return ResourceManager.GetString("ErrorPasswordsCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} является обязательным полем.
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите файл скина.
        /// </summary>
        public static string ErrorSkinEmpty {
            get {
                return ResourceManager.GetString("ErrorSkinEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скин должен быть формата png.
        /// </summary>
        public static string ErrorSkinFormat {
            get {
                return ResourceManager.GetString("ErrorSkinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина {2}.
        /// </summary>
        public static string ErrorStringMinLength {
            get {
                return ResourceManager.GetString("ErrorStringMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не может быть email адресом.
        /// </summary>
        public static string ErrorUserNameAsEmail {
            get {
                return ResourceManager.GetString("ErrorUserNameAsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешены латинские буквы и цифры, а также символы - и  _.
        /// </summary>
        public static string ErrorUserNameChars {
            get {
                return ResourceManager.GetString("ErrorUserNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя не может быть пустым.
        /// </summary>
        public static string ErrorUserNameEmpty {
            get {
                return ResourceManager.GetString("ErrorUserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким именем уже существует.
        /// </summary>
        public static string ErrorUserNameExists {
            get {
                return ResourceManager.GetString("ErrorUserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gonts.
        /// </summary>
        public static string Gonts {
            get {
                return ResourceManager.GetString("Gonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть пароль.
        /// </summary>
        public static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Структура папок клиента проверена.
        /// </summary>
        public static string LauncherClientAllFolders {
            get {
                return ResourceManager.GetString("LauncherClientAllFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Структура папок неверная.
        /// </summary>
        public static string LauncherClientNoFolders {
            get {
                return ResourceManager.GetString("LauncherClientNoFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверные данные для входа.
        /// </summary>
        public static string LauncherErrorAuth {
            get {
                return ResourceManager.GetString("LauncherErrorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия лаунчера устарела.
        /// </summary>
        public static string LauncherInvalidVersion {
            get {
                return ResourceManager.GetString("LauncherInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешная авторизация.
        /// </summary>
        public static string LauncherSuccessAuth {
            get {
                return ResourceManager.GetString("LauncherSuccessAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия лаунчера валидная.
        /// </summary>
        public static string LauncherValidVersion {
            get {
                return ResourceManager.GetString("LauncherValidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ник.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        public static string PlayerBalance {
            get {
                return ResourceManager.GetString("PlayerBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль игрока.
        /// </summary>
        public static string PlayerProfile {
            get {
                return ResourceManager.GetString("PlayerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешний вид игрока.
        /// </summary>
        public static string PlayerView {
            get {
                return ResourceManager.GetString("PlayerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рубли.
        /// </summary>
        public static string Rubles {
            get {
                return ResourceManager.GetString("Rubles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуть стандартный скин.
        /// </summary>
        public static string SetDafaultSkin {
            get {
                return ResourceManager.GetString("SetDafaultSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать пароль.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы клиента прошли проверку.
        /// </summary>
        public static string SuccessClientFilesCheck {
            get {
                return ResourceManager.GetString("SuccessClientFilesCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это имя не занято.
        /// </summary>
        public static string UserNameNoExists {
            get {
                return ResourceManager.GetString("UserNameNoExists", resourceCulture);
            }
        }
    }
}
